# **Aula 1 - 02/02/2021**

### Series e Dataframes usando Pandas

Python tem diversas estruturas para armazenamento de dados. 

Algumas delas são "internas": listas, tuplas, conjuntos, dicionários.

Outras, precisam de bibliotecas específicas: ndarray (Numpy), Series e DataFrames (Pandas).

### Listas

* Mutáveis
* Ordenadas
* Heterogêneas
* Indexada por posição
* Delimitada por colchetes []

In [1]:
lista = ['casa', 1.0, 3 ,[1,2,3]]
lista

['casa', 1.0, 3, [1, 2, 3]]

In [2]:
type(lista)

list

Chamando elementos da lista:

In [3]:
lista[0]

'casa'

In [4]:
lista[1]

1.0

In [5]:
lista[2]

3

In [6]:
lista[3]

[1, 2, 3]

In [7]:
lista[3][2]

3

Um problema sério: Operações com listas

In [8]:
a = [1,2,3]
a

[1, 2, 3]

Forma errada:

In [9]:
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

Forma correta:

In [10]:
b = []
for i in a:
    b.append(i*3)
b

[3, 6, 9]

For é um meio bastante lento do ponto de vista de eficiência computacional.

### Dicionários
* Mutáveis
* Não ordenados
* Heterogêneos
* Indexada por chaves
* Delimitada por chaves {}

In [11]:
Dicionario = {"Nome": "Vini", "Idade": 18, "Cidade": "Esperança"}
Dicionario

{'Nome': 'Vini', 'Idade': 18, 'Cidade': 'Esperança'}

Indexação por chaves

In [12]:
Dicionario["Nome"]

'Vini'

In [13]:
Dicionario['Idade']

18

In [14]:
Dic = {"A": {"Abel":939291919, "Adriano": 98915645}}
Dic

{'A': {'Abel': 939291919, 'Adriano': 98915645}}

In [15]:
Dic["A"]["Adriano"]

98915645

#### ndarray - Numpy
A biblioteca Numpy é a biblioteca numérica do Python, e é a base de todas as grandes bibliotecas do ecossistema Python de computação científica e análise de dados, como Scipy, Matplotlib e a própria Pandas.

A biblioteca Numpy cria uma nova estrutura de dados, chamada de ndarray, que possue algumas similaridades com listas, mas alguns poderes a mais, com destaque para a capacidade de vetorização, que possibilita que qualquer operação feita com a estrutura seja feita elemento a elemento sem a necessidade de um laço para acessar esses elementos, tornando, assim, a operação computacionalmente mais eficiente.

<img src="https://miro.medium.com/max/760/1*00pL0zLnfI7y8d5G1aQrHA.jpeg" alt="imagem" width="200">

**OBS: Importação de bibliotecas**

In [16]:
import numpy as np

In [17]:
np.array([-2, 4.3, 7, 9])

array([-2. ,  4.3,  7. ,  9. ])

Existem várias formas de criar arrays, pode ser através do método np.array(): 

#### 1. Usando uma lista: `np.array([])`

In [18]:
arr = np.array([-2, 4, 7, 9])
arr

array([-2,  4,  7,  9])

String > complex > float > int

In [19]:
1 + 2.0

3.0

#### 2. Usando o método arange: `np.arange(Ínicio, fim, passo)`

In [48]:
arr = np.arange(1, 150, 5)
arr

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146])

#### 3. usando o método linspace: `np.linspace(inicio, fim, quantidade)`

In [49]:
arr = np.linspace(1, 150, 5)
arr

array([  1.  ,  38.25,  75.5 , 112.75, 150.  ])

#### 4. Outros métodos:

In [55]:
arr1 = np.empty(5) # Array vazia com o método empty() normalmente a saída é lixo de memória ou zeros
arr1

array([  1.  ,  38.25,  75.5 , 112.75, 150.  ])

In [53]:
arr2 = np.eye(6) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos
print(arr2, '\n')

arr3 = np.zeros(8) # array contendo 8 'zeros'
print (arr3, '\n')

arr4 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

[0. 0. 0. 0. 0. 0. 0. 0.] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Vamos criar as arrays A e B para fazer operações com elas


##### *Podemos usar o np.nan para preencher espaços vazios e realizar operações.*

In [92]:
A = np.arange(10)
B = np.arange(10, 40, 3)
C = np.array([1, 2, 3, 4, 5 ,6 ,7 ,8 ,np.nan, np.nan])

print(' A: ', A, '\n', 'B: ', B, '\n', 'C: ', C)

 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [10 13 16 19 22 25 28 31 34 37] 
 C:  [ 1.  2.  3.  4.  5.  6.  7.  8. nan nan]


In [93]:
somar = A + B + C
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar )
print('subtrair: ', subtrair )
print('dividir: ', dividir )
print('multiplicar: ', multiplicar)

somar:  [11. 16. 21. 26. 31. 36. 41. 46. nan nan]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [0.         0.07692308 0.125      0.15789474 0.18181818 0.2
 0.21428571 0.22580645 0.23529412 0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


## Indexação

![Image of Yaktocat](http://www.scipy-lectures.org/_images/numpy_indexing.png)